apps/urls.py
from django.urls import include, path
from django.contrib import admin
from django.urls import path, include # new


# from theme import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 

    # Home or http:<site_addr>/
    path('', include('bookmarks.urls', namespace='bookmarks')),
]

books_cbv/urls.py
from django.urls import path

from . import views

app_name = 'books_cbv'

urlpatterns = [
  path(''
  , views.BookmarkList.as_view(), name='bookmark_list'),

  path('starred'
  , views.BookmarkStarred.as_view(), name='bookmark_starred'),
  
  path('new'
  , views.BookmarkCreate.as_view(), name='bookmark_new'),
  
  path('edit/<int:pk>'
  , views.BookmarkUpdate.as_view(), name='bookmark_edit'),
  
  path('delete/<int:pk>'
  , views.BookmarkDelete.as_view(), name='bookmark_delete'),
]

books_cbv/models.py
from django.db import models
from django.urls import reverse

from urllib.parse import urlparse 

class Tag(models.Model):
    name = models.CharField(max_length=300, unique = True)

    def __str__(self):
        return self.name 

class SiteBookmark(models.Model):
    # Max URL size has 3000 bytes
    #url   = models.CharField(max_length=4000)
    url = models.URLField()
    name = models.CharField(max_length= 8000, blank = True, null = True)    
    starred = models.BooleanField(blank = True)
    brief = models.TextField(blank = True, null = True)
    tags = models.ManyToManyField(Tag, blank = True)

    def __str__(self):
        return "name = {name} ; url = {url}".format(name = self.name, url = self.url)

    def get_absolute_url(self):
        return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

    def hostname(self):        
        u = urlparse(self.url)
        return u.hostname

    def isVideo(self):
        hostname = urlparse(self.url).hostname
        return "youtube.com" in hostname 

books_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q 

from books_cbv.models import SiteBookmark

# Template files 
tpl_main = "books_cbv/book_list.html"
tpl_forms = "books_cbv/form.html"

class BookmarkList(ListView):
    template_name = tpl_main
    model = SiteBookmark

    def get_queryset(self):

        view = self.request.GET.get("view")
        
        if view and view == "latest":               
            return self.model.objects.all().order_by("id").reverse()

        if view and view == "starred":               
            return self.model.objects.filter(starred = True)

        query2 = self.request.GET.get('search')
        if query2:
            return self.model.objects.filter( Q(name__contains = query2) 
                                            | Q(url__contains = query2) )
        
        #print(" [BookmarkList] kwargs = " + str(self.kwargs))
        return self.model.objects.all()


class BookmarkStarred(ListView):
    template_name = tpl_main
    # model = SiteBookmark

    def get_queryset(self):
        lst = SiteBookmark.objects.filter(starred = True)
        return lst 

class BookmarkCreate(CreateView):
    template_name = tpl_forms
    model = SiteBookmark
    fields = ['name', 'url', 'starred', 'brief', 'tags']
    success_url = reverse_lazy('books_cbv:bookmark_list')

class BookmarkUpdate(UpdateView):
    template_name = tpl_forms
    model = SiteBookmark
    fields = ['name', 'url', 'starred', 'brief', 'tags']
    success_url = reverse_lazy('books_cbv:bookmark_list')

class BookmarkDelete(DeleteView):
    template_name = "books_cbv/book_confirm_delete.html"
    model = SiteBookmark
    success_url = reverse_lazy('books_cbv:bookmark_list')

books_cbv/templates/books_cbv/book_confirm_delete.html
{% block content %}

<h2><a href="{% url 'books_cbv:bookmark_list' %}">Bookmarks</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

books_cbv/templates/books_cbv/book_list.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
       <title> Bookmark Manager</title>        
       
    </head>
    <body>
            {% block content %}
            <h1>Bookmarks Storage</h1>
            
            <div class="top">
                    <a href="/">List all</a>
                    ; <a href="/?view=latest">Latest</a>
                    ; <a href="/?view=starred">Starred</a>
                    ; <a href="{% url 'books_cbv:bookmark_new' %}">Add new entry</a>
                    
                    <form method='GET'>
                            <input type='text' name='search' value='{{ request.GET.search }}'>
                            <input class="button" type='submit' value="Search">
                    </form>       
            </div>
            
            <div class='content'>    
                {% for bookmark in object_list %}
                    <div class = "item">   
                        <h5> ID = {{ bookmark.id }} / <a target='_blank' title="{{bookmark.brief}}" href="{{ bookmark.url }}"> {{ bookmark.name | default:bookmark.url }} </a></h5>
                        <a href="{% url 'books_cbv:bookmark_edit' bookmark.id %}">edit</a>
                        </br> <a href="{% url 'books_cbv:bookmark_delete' bookmark.id %}">delete</a>                           
                        </br> starred = {{ bookmark.starred }} 
                        </br> Domain = {{ bookmark.hostname }}
                                    
                        <p> {{ bookmark.brief }} </p>
            
                    </div>                            
                {% endfor %}
                
            
            </div>
            
            {% endblock %}
    </body>
</html>

books_cbv/templates/books_cbv/form.html
{% block content %}

<h1> Edit/Create Book Entry </h1>

<h2><a href="{% url 'books_cbv:bookmark_list' %}">Web Site Bookmark</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}