apps/urls.py
from django.urls import include, path
from django.contrib import admin
from django.urls import path, include # new


# from theme import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 

    # Home or http:<site_addr>/
    path('', include('bookmarks.urls', namespace='bookmarks')),
]

bookmarks/urls.py
from django.urls import path, include
import django.views.generic.base as dvgb

from . import views

from . import rest_views 

app_name = 'bookmarks'

urlpatterns = [
  # Redirect straight to template 
  # see: https://stackoverflow.com/questions/3402708/
   path('', dvgb.TemplateView.as_view(template_name = 'index.html'), name = 'home')

  ,path('accounts/signup', views.signup, name='signup')

  ,path('items', views.BookmarksList.as_view(), name = "bookmark_list")

  ,path('items/new', views.BookmarkCreate.as_view(), name='bookmark_new')
  ,path('items/edit/<int:pk>', views.BookmarkUpdate.as_view(), name='bookmark_edit')  
  ,path('items/delete/<int:pk>', views.BookmarkDelete.as_view(), name='bookmark_delete')

  # Bookmarklet URL route for making easier to add new items 
  # through bookmarklet Javascript 
  ,path("items/add", views.bookmark_add_item_bookmarklet)

  ,path("items/extract_metadata", views.extract_metadata)
  ,path("items/view/<int:itemID>", views.document_viewer)

  #,path("snapshot/get", views.fetch_itemsnapshot)
  
  ,path("snapshot/file/<fileID>/<fileName>", views.get_snapshot_file)
  ,path("pdf2html/<fileUUID>/<fileName>", views.pdf2hml)
  ,path("thumbnail/<fileUUID>", views.document_thumbnail)

  ,path('options/video_toggle', views.video_toggle, name='options_video_toggle')
  # ----------------------------------------------------#

  ,path('search/list', views.SavedSearchList.as_view(), name='bookmark_savedsearch_list')
  ,path('search/new', views.SavedSearchCreate.as_view(), name='bookmark_savedsearch_new')
 
  ,path('tags', views.TagList.as_view())
  #----------------------------------------------------#

  ,path('collection/list', views.CollectionList.as_view(), name='bookmark_collection_list')
  ,path('collection/new',  views.CollectionCreate.as_view(), name = 'bookmark_collection_new')

  # ----------------- REST API ------------------------#
  ,path("api/items",                views.Ajax_Items.as_view())  
  ,path("api/item_upload",          views.item_upload)

  ,path("api/item",                 views.rest_item)  
  ,path("api/bulk",                 views.rest_bulk_action)  
  ,path("api/related",              views.Ajax_ItemRelated.as_view())  
  #,path("api/collections",     views.Ajax_Collection_List.as_view())  
  ,path("api/collections",          views.Ajax_Collections.as_view())  
  ,path("api/collections/items",    views.Ajax_Collection_List.as_view())  

  ,path("api/collections/add_item", views.Ajax_Collection_AddItem.as_view())  
  ,path("api/search",               views.Ajax_ItemSearch.as_view())
  ,path("api/tags",                 views.Ajax_Tags.as_view()) 

   # ======= Django-Rest Framework ============================#
    # Authentication endpoint 
#  , path('api2/login',           include('rest_auth.urls')              )
  , path('api2/items',           rest_views.RestItems.as_view()         )
  , path('api2/items/<int:pk>',  rest_views.RestItemsDetail.as_view()  )
  , path('api2/tags',            rest_views.RestTags.as_view()          )
  , path('api2/tags/<int:pk>',   rest_views.RestTagsDetail.as_view()   )

]

bookmarks/views.py
import typing
from typing import Dict, List, NamedTuple
from django.db.models.expressions import OrderBy
from django.forms.widgets import FILE_INPUT_CONTRADICTION

from django.http import HttpResponse, FileResponse, Http404
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q 
import django.shortcuts as ds 
import django.core.exceptions
from django.forms.utils import ErrorList
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
import socket 

from bookmarks import dutils

from bookmarks.models import SiteBookmark, SavedSearch, Collection \
    , FileSnapshot, Tag, Tag2

import bookmarks.models as bm

import django.core.paginator as pag 
from django.core.handlers.wsgi import WSGIRequest
from django.db.models.query import QuerySet
from django.core.paginator import Page

import django.utils.http
from django.contrib.sessions.backends.db import SessionStore
from django.db.models.functions import Lower
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Count
import logging
#from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import django.core.paginator as dj_paginator 

from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.dispatch import receiver


import bs4 
import urllib
import shlex 

import typing as ty
from functools import reduce 

import PyPDF2
import io 

# --- Imports for REST APIs -----------------------#
from django.http import JsonResponse
import json 

# Template files 
tpl_main           = "bookmark_list.html"
tpl_forms          = "bookmark_form.html"
tpl_confirm_delete = "bookmark_confirm_delete.html"

# User agent for web scrapping 
## BROWSER_USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"

BROWSER_USER_AGENT = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"


@receiver(user_logged_in)
def on_login(sender, user, request, **kwargs):
    logger = logging.getLogger(__name__)
    logger.info(f" <LOGIN> User account {user} logged in.")


@receiver(user_logged_out)
def on_logout(sender, user, request, **kwargs):
    logger = logging.getLogger(__name__)
    logger.info(f" <LOGOUT> User account {user} logged out.")


class SignUpForm(UserCreationForm):
    username = forms.CharField( max_length =30
                              , required   = True
                              , help_text  ='Optional.')
    
    email = forms.EmailField( max_length =254
                            , required   =True
                            , help_text  ='Required. Inform a valid email address.')
    
    class Meta:
        model = bm.Account
        fields = ('username', 'email', 'password1', 'password2', )

def signup(request):

    logger = logging.getLogger(__name__)

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username     = form.cleaned_data.get('username')
            email        = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user         = django.contrib.auth.authenticate(email=email, password=raw_password)
            django.contrib.auth.login(request, user)
            return ds.redirect('/items')
    else:
        form = SignUpForm()

    logger.info("User registered Ok.")
    return ds.render(request, 'registration.html', {'form': form})


class BookMarkFilter(NamedTuple):
    view:     str 
    title:    str
    callback: typing.Any 

class BookmarksList(LoginRequiredMixin, ListView):

    logger = logging.getLogger(__name__)

    # --- overriden variables --------
    model         = SiteBookmark
    template_name = tpl_main
    paginate_by  = 15
    context_object_name = "object_list"
    
    null_view = BookMarkFilter("null", "Listing items by latest added", None)

    filter_dispatch: Dict[str, BookMarkFilter] = {}    
    empty_query = model.objects.none()

    def __init__(self):
        super(BookmarksList, self).__init__()
        self.start()

        # ---------- Set callbacks ------------#   
    def start(self):
        self.add_filter("id",           "Select single item by ID",        self.filter_by_id)
        self.add_filter("all",          "Listing all items",               self.filter_all)
        self.add_filter("starred",      "Starred items",                   self.filter_starred)
        self.add_filter("removed",      "Removed items",                   self.filter_removed)
        self.add_filter("doctype",      "Items fitered by type",           self.filter_doctype)
        self.add_filter("search",       "Search results",                  self.filter_search)
        self.add_filter("domain",       "Items filtered by domain",        self.filter_domain)
        self.add_filter("collection",   "Collection items",                self.filter_collection)
        self.add_filter("tag-name",     "Filter tag by name",              self.filter_by_tag_name)
        self.add_filter("created-date", "Filter by created date",          self.filter_by_created_date)
        self.add_filter("upload",       "File uploads",                    self.filter_uploads)
        self.add_filter("snapshot",     "Items with snapshots",            self.filter_has_snapshot)
        return self 

    def add_filter(self, view: str, title: str, callback):
        self.filter_dispatch[view] = BookMarkFilter(view = view, title = title, callback = callback)

    def order_query(self, query: QuerySet) -> QuerySet:
        ORDER_BY_NEWEST = "new"       # Order items by newest added (by id)
        ORDER_BY_OLDEST = "old"       # Order items by oldest added (by id)
        ORDER_BY_UPDATE = "updated"   # Order items by last updated 
        order: str = self.request.GET.get("order") or ORDER_BY_NEWEST
        print(" [TRACE] ORDER = ", order)

        # logging.debug(f" Order search results by {order}")

        if order == ORDER_BY_NEWEST:
            ## print(" [TRACE] Order by newest")
            return query.order_by("id").reverse()
        elif order == ORDER_BY_OLDEST:
            ## print(" [TRACE] Order by oldest")
            return query.order_by("id")
        elif order == ORDER_BY_UPDATE:
            ## print(" [TRACE] Order by last update")
            return query.order_by("updated").reverse()
        else:
            # Default: ORDER_BY_NEWEST
            return query.order_by("id").reverse()

    # Determines the query => Called before get_context_data()
    def get_queryset(self) -> QuerySet:
        ## print(" [TRACE] get_queryset() called. Ok. ")
        filter_: str = self.request.GET.get("filter", "")                
        query: QuerySet = self.empty_query
        if filter_ in self.filter_dispatch.keys():            
            query = self.filter_dispatch[filter_].callback() 
        else:                    
            query = self.filter_all()
        return self.order_query( query )

    # Return context data dictionary to the rendered template 
    def get_context_data(self, **kwargs):        
        print(" [TRACE] get_context_data() called. Ok. ")
        # Context variable is a dictionary which contains the variables
        # visible in the Django template files 
        context = super(BookmarksList, self).get_context_data(**kwargs)
        assert context is not None 
        ## print(f" Trace = { self.context_object_name }")
        query: QuerySet = context[self.context_object_name]
        assert query is not None 
        narrow = self.request.GET.get("narrow") or "off"
        search = self.request.GET.get("search") or ""
        if narrow != "off":
            query = query.filter( title__contains = search) 
            pass 
        rFilter = self.request.GET.get("filter") or ""
        rA0     = self.request.GET.get("A0") or ""
        # rQuery  = self.request.get("query")
        rQuery  = urllib.parse.quote(self.request.GET.get("query") or "")
        rMode   = self.request.GET.get("mode")   or ""
        rOrder  = self.request.GET.get("order")  or ""
        url_state = "filter={filter}&A0={A0}&mode={mode}&query={query}&order={order}"\
            .format(  filter = rFilter 
                    , A0     = rA0 
                    , query  = rQuery
                    , mode   = rMode 
                    , order  = rOrder 
                    )   
        ## print(f" [TRACE] get_context_data() =>> url_state = {url_state}") 
        view = self.request.GET.get("filter") or "null"
        ## print(f" [TRACE] get_context_data() =>> view = {view}")
        title = (self.filter_dispatch.get(view) or self.null_view).title 
        tag_description = ""
        if view == "doctype":
            title = title + ": " + (self.request.GET.get("A0") or "")
        elif view == "collection":
            coll_id = self.request.GET.get("A0")
            coll = Collection.objects.get(id = coll_id, owner = self.request.user)
            title = title + " : " + coll.title 
        elif view == "tag-name":
            title = title + " : " + rA0 
            tag: Tag2 = Tag2.objects.get(name = rA0, owner = self.request.user)
            tag_description = tag.description
            ## tag_description = self.
        context["page_title"] = title 
        context['count'] = self.get_queryset().count()
        context["url_state"] = url_state
        context["tag_description"] = tag_description
        order = self.request.GET.get("order") or "new" 
        if   order == "new": context["item_sorting"] = "Newest items"
        elif order == "old": context["item_sorting"] = "Oldest items"

bookmarks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>    

    <head>
        <title> Bookmark Manager</title>        

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <link rel="icon" href={% static "favicon.png" %} type="image/png" sizes="16x16"> 
    <!--     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
            <!--  Reference Prevent Page Zooming in Mobile Browsers: https://davidwalsh.name/zoom-mobile-browsers -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> <!--320-->
        <!-- Bootstrap CSS -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link rel="stylesheet" href={% static "bootstrap.min.css" %}>
        <link rel="stylesheet" href="/static/style.css?rnd=10">        
        
       <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->

       <style>
       </style>

        <script>
                // Hide DOM element. selector is the element's css selector.
                function DOM_hide(selector)
                {                 
                    m = document.querySelector(selector);
                    if(m == null){ alert(" Error: element not found");  }
                    m.style.display = "block";
                    m.style.visibility = "hidden";
                }

                // Show DOM element. selector is the element's css selector.
                function show_DOM_element(selector)
                {
                    var m = document.querySelector(selector);
                    if(m == null){ alert(" Error: element not found");  }
                    m.style.display = "block";
                    m.style.visibility = "visible";
                }

                // Toggle DOM element 
                function DOM_toggle(selector)
                {
                    var m = document.querySelector(selector);
                    if(m == null){ alert(" Error: element not found");  }
                    m.style.display = "block";
                    var v = window.getComputedStyle(m);
                    // if(m.style.visibility == "" || m.style.visibility == "visible")
                    if(v.visibility == "visible")
                    {
                        console.log(" [TRACE] => Hide element");
                        m.style.visibility = "hidden";
                    } else {
                        console.log(" [TRACE] => Show element");
                        m.style.visibility = "visible";
                    }
                        
                }                              
        </script>
   
    </head>

    <body>
        
        <div id="content">
                {% block content %}
                {% endblock %}
        </div><!-- content -->

    </body>


</html>

bookmarks/templates/base2.html
<!DOCTYPE html>
<html>    
    {% include 'include_header.html' %}

    <body>
        {% include 'include_menu.html' %}
        
        <div class="content">
             {% block content %}{% endblock %}
        </div><!-- content -->

    </body>
</html>

bookmarks/templates/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'bookmarks:bookmark_list' %}">Bookmarks</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

bookmarks/templates/bookmark_form.html
{% extends "base.html" %}

{% block content %}

<div class="container">
        <h1> Edit/Create Bookmark Entry </h1>

        <!-- <h2><a href="{% url 'bookmarks:bookmark_list' %}">Web Site Bookmark</a>: Edit</h2> -->
        
        <form method="post">{% csrf_token %}
            <input class="btn-sm btn-primary" type="submit" value="Submit">
            <input class="brn-sm btn-primary" type="reset"  value="Reset">
            <table biorder="1"> 
                    <!-- {{ form.as_p }} -->
                    {{ form.as_table }}
            </table>                        
        </form>        
</div>

{% endblock %}

bookmarks/templates/collection_list.html
{% extends "base2.html" %}

{% block content %}

<a class="btn btn-info" href="/search/new"  title="Saved search">Add saved search</a>

<a id="btn-create-new-collection" class="btn btn-info" href="#"  
    title="New collection">New collection</a>

<div id="bookmark-list" class="container">       

    {% for collection in object_list %}
        
        <div class="well item div-collection-container"
             data-id    = "{{ collection.id    }}"
             data-title = "{{ collection.title }}"
             data-desc  = "{{ collection.description }}"
            >   

            <a  href="/items?filter=collection&A0={{ collection.id }}" 
                title="{{ collection.description }}"> 
                {{ collection.title }} 
            </a>


            
            </br>
            <p> {{ collection.description }} </p>
  
            <a class="btn btn-info btn-collection-edit" 
               title="Edit current collection.">Edit</a>            

            <a class="btn btn-info btn-collection-delete"                 
                title="Delete current collection.">Delete</a>
        </div>                            
    {% endfor %}
    
</div>

{% endblock %}

bookmarks/templates/include_header.html
{% load static %}
<!DOCTYPE html>
<head>
        <title> Bookmark Manager - {{ page_title }} </title>        

        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <link rel="icon" href={% static "images/favicon.png" %} type="image/png" sizes="16x16" /> 
    <!--     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
            <!--  Reference Prevent Page Zooming in Mobile Browsers: https://davidwalsh.name/zoom-mobile-browsers -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> <!--320-->
        <!-- Bootstrap CSS -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link rel="stylesheet" href={% static "bootstrap.min.css" %} />
        <link rel="stylesheet" href="/static/style.css?rnd=10" />        
        
        <!-- TOAST JavaScript  Library -->
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

       
       <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
<!-- 
       <script type="text/javascript" src  ="/static/dialog-polyfill.js"></script>
       <link   rel="stylesheet"       href ="/static/dialog-polyfill.css" /> -->
        
       <script type="module" src="/static/dialogs.js"></script>
       
       <script type="module" src="/static/main.js"></script>
      <!--  <script type="text/javascript" src="/static/main.js"></script> -->
     
        <script type="module" src="/static/tsutils.js"> </script>
        <script type="module" src="/static/tsmain.js"> </script>

        <script type="module">
            import * as tsutils from "/static/tsutils.js";
            import * as tsmain  from "/static/tsmain.js";
            window["tsutils"] = tsutils.tsutils;
            window["tsmain"] = tsmain;

        </script>
      
        <script type="text/javascript">
            generated_token = "{{ csrf_token }}";
        </script>
    </head>

bookmarks/templates/index.html
{% extends "base.html" %}

{% block content %}


{% if user.is_authenticated %}
        Welcome user: {{ request.user.username }} / logged as {{ request.user.email }}                
        <ul>
            <li><a class="btn-sm btn-primary" href="/accounts/logout">Logout</a></li>
        </ul>
        
{% else %}
        Welcome user: Anonymous user.
        <ul>
            <li>
                <a class="btn-sm btn-primary" href="/accounts/login" 
                   title="Click here to login (authenticate)">Login</a>

                <a class="btn-sm btn-primary" href="/accounts/signup" 
                   title="Click here to sign up (register)">Sign up</a>           
            </li>                
        </ul>        
{% endif %}



<h1> Index </h1>

<h3>Logout</h3>

<ul>
    <li>  <a href='/accounts/logout'>User Logout</a> </li>
</ul>


<h3> Saved Search </h3>

<ul>    
    <li> <a href='/search/list'>Saved searches</a> </li>
    <li> <a href='/search/new'>Add new saved search</a> </li>
</ul>

Search Items:

<div class="">

            <input type="hidden" name="filter" value="search" /> 
            <input id="search-entry" type='text' name='search' value='{{ request.GET.search }}' > 
            <input id="btn-search"    class="btn-sm btn-info" type='button' value="Search" > 
            <input id="btn-top-clear" class="btn-sm btn-info" type="reset" value="Clear">
</div>      
<h3> Items </h3>

<ul>
    <li>  <a href='/items/new'>Add item</a> </li>
    <li>  <a href='/items?filter=all'>All bookmarks</a> </li>
    <li>  <a href='/items?filter=starred'>Starred bookmarks</a>  </li>    
    <li>  <a href='/items?filter=removed'>Removed bookmarks</a> </li>
</ul>

<h3> Collection </h3>

<ul>    
    <li> <a href='/collection/list'>List collections</a> </li>
    <li> <a href='/collection/new'>Add new collection</a> </li>
</ul>

<h3>Filter by Bookmark type </h3>

General: 

<ul>    
    <li> <a href='/items?filter=doctype&A0=search%20engine'>Search Engine</a> </li>
    <li> <a href='/items?filter=doctype&A0=news'>News outlets</a> </li>
    <li> <a href='/items?filter=doctype&A0=community'>Online Forums and Communities</a> </li>
    <li> <a href='/items?filter=doctype&A0=online%20store' 
            title="Filter online store bookmarks such as Amazon, Ebay, BestBuy, Aliexpress ..." 
          >Online Store</a> </li>
    <li> <a href='/items?filter=doctype&A0=follow'>Followed social media accounts</a> </li>
</ul>

Documents: 

<ul>
    <li> <a href='/items?filter=doctype&A0=book'>Books or online books</a> </li>    
    <li> <a href='/items?filter=doctype&A0=paper'>Papers</a> </li>        
    <li> <a href='/items?filter=doctype&A0=thesis'>Thesis: phd, master, undergrad thesis</a> </li>    
    <li> <a href='/items?filter=doctype&A0=reference%20card'>Reference card, cheat sheet</a> </li>       
</ul>

Media: 

<ul>
    <li> <a href='/items?filter=doctype&A0=music'>Music</a> </li>
    <li> <a href='/items?filter=doctype&A0=video'>Video</a> </li>
    <li> <a href='/items?filter=doctype&A0=youtube%20channel'>Youtube Channel</a> </li>        
</ul>

Tooling: 

<ul>
    <li> <a href='/items?filter=doctype&A0=online_tool'>Online tool, tooling</a> </li>
    <li> <a href='/items?filter=doctype&A0=developer_tool'>Developer tool, tooling</a> </li>    
</ul>


{% endblock %}

bookmarks/templates/registration.html
{% extends 'base.html' %}

{% block content %}
  
<h2>Sign up</h2>
  
  <form method="post">
    <button class="btn-sm btn-primary" type="submit">Sign up</button>

    <table border="1">
        {% csrf_token %}
        {{ form.as_table }}
    </table>   
  </form>
{% endblock %}

bookmarks/templates/savedsearch_list.html
{% extends "base2.html" %}

{% block content %}

    {% for savedsearch in object_list %}
        
    <div class = "well item ">   
        <a class="item-bookmark-link" href="/items?filter=search&query={{ savedsearch.search|urlencode }}" title="{{ savedsearch.description }}" > {{ savedsearch.search }} </a>
        <p> {{ savedsearch.description }} </p>
    </div>                            
    {% endfor %}

{% endblock %}

bookmarks/templates/tags_list.html
{% extends "base2.html" %}

{% block content %}

<div id="bookmark-list" class="container">       

    {% for tag in object_list %}
        
        <div class = "well item ">   

            <a  href="/items?filter=tag-name&A0={{ tag.name }}" 
                title="{{ tag.name }}"> 
                {{ tag.name }} 
            </a>

            <br/> 
            <p> {{ tag.description }} </p>
            <br/>

            <button class="btn-sm btn-info btn-tag-update" 
                    data-id="{{ tag.id }}" data-name="{{ tag.name }}" data-description="{{ tag.description }}" >Edit</button> 
            
            <button class="btn-sm btn-info btn-tag-delete" 
                    data-id="{{ tag.id }}" data-name="{{ tag.name }}" data-description="{{ tag.description }}" >Delete</button> 
            <br/>            
  
        </div>                            
    {% endfor %}
    
</div>

{% endblock %}